### ISSUE TITLE
Suggestions API container doesn't start | failed to connect to sql-data:1433

### ISSUE THREAD

**Issue by IoTFier** [Microsoft/SmartHotel360-Azure-backend#11]
Hello all, yesterday, I fetched changes from the backend source repo and also updated my Docker for Windows to the latest stable version 17.20.0-ce-win46 (15048)  

After these updates, the "docker-compose build" resulted in all API containers build and running except one - suggestion-api_1. Looking at the logs from docker-compose build.. I found that login for the user sa failed for suggestions-api_1, profiles-api_1 and for hotels-api_1.

Have anyone faced this issue? Are you able to connect to the sqlserver instance created in this docker-compose build? Where should I look for connection details to connect to that SQL server instance including initial sa pw which is causing this error?

Your help will be appreciated.
Thanks you

![image](https://user-images.githubusercontent.com/26844611/34780695-68ea5b92-f5e9-11e7-9e56-4879f20b10f2.png)

![image](https://user-images.githubusercontent.com/26844611/34780250-38287d0a-f5e8-11e7-907a-f9c11558ad2e.png)

![image](https://user-images.githubusercontent.com/26844611/34780410-acda1ce4-f5e8-11e7-80c3-2e6429147e59.png)

**Comment by eiximenis** [comment]
Hi!
Some questions :)

1. Did you tried to start 1st only the databases  with

```
docker-compose up sql-data reviews-data tasks-data
```` 

and when all databases are ready just do a new `docker-compose up` to start the remaining containers? Sql Server starts some time to be ready to accept connections and the demo code is not resilient to this.

2. Are the other APIs that are running agains Sql server container working?

3. SQL Server requires 3+ GB on the machine. Did you set least 4GB of RAM to the Docker virtual machine?

**Comment by IoTFier** [comment]
Hi Eximenis, thank you for the timely input.

I just finished that step and now my containers are up and running ...
Yes, I have docker set up with 4gb as prescribed. 
Have you tried to connect to these sql server and postgres server from Visual Studio? If yes, where can I find the connection details related to the containers hosting these sql server and postgres server?

Thank you
................................................................
read.me instructions to be followed are at ...
![image](https://user-images.githubusercontent.com/26844611/34782252-bfbdd0da-f5ed-11e7-9461-
cbaca077174c.png)

**Comment by IoTFier** [comment]
I tried setting up the connection in the database with SQL Server Authentication for sa using SA_PASSWORD is the database system administrator (userid = 'sa') password used to connect to SQL Server once the container is running. from - https://hub.docker.com/r/microsoft/mssql-server-linux/

Used the IP address (below the gateway address) of the container by running "docker inspect src_sql-data_1" . But the test connection failed.

Anyone lucky to found the required connection details yet ?

![image](https://user-images.githubusercontent.com/26844611/34887410-08e5d65a-f78c-11e7-8f0a-642a837959a2.png)

**Comment by IoTFier** [comment]
Hello Community,
Any thought on this connectivity issue? 
Thanks

**Comment by eiximenis** [comment]
Hi,
If you try to connect with SQL Management studio, what is the error?

**Comment by IoTFier** [comment]
Here is the error in SQL Mgmt studio 17.4

![image](https://user-images.githubusercontent.com/26844611/35113566-7de731a0-fc47-11e7-9709-81cf7e4adaee.png)

**Comment by eiximenis** [comment]
MMmm...
SQL Server listens for its port 1433. If you are using the container's IP you have to use the container's port. Try connecting using port 1433 instead of 6433 (which is the host port).

**Comment by IoTFier** [comment]
I understand SQL Server listens to 1433 but the host IP port is 6433 (see the screenshot above).
The Docker file for SQL Server Linux or any other target OS refers to 1433 as the default port required by the SQL Server application running in the container. For the external network to connect to SQLServer the mapping from the host IP in this case 6433 to 1433 needs to be defined and executed as a part of the docker-compose up sql-data reviews-data tasks-data. But seeing the docker-compose YML file, it refers only to the image and the docker-compose-override.yml refers to mapping up the host port 6433 to 1433. _So in theory in SSMS I should be able to connect using localhost:6433 , SA and SA's password. But it didn't work either, including providing the [IP address of my pc/host]:6433 as well.

![image](https://user-images.githubusercontent.com/26844611/35182049-0f13b134-fd93-11e7-8449-4b9a0c466d34.png)
![image](https://user-images.githubusercontent.com/26844611/35182053-1c567d7c-fd93-11e7-96df-44794da03d71.png)
![image](https://user-images.githubusercontent.com/26844611/35182078-7ca291fc-fd93-11e7-8be8-6507467db349.png)


**Tried your recommendation, here is the error with that one ..**
![image](https://user-images.githubusercontent.com/26844611/35182013-268c4b6a-fd92-11e7-848e-34df78f210be.png)

**Comment by eiximenis** [comment]
Ok.
Could you type `docker logs <id>` where id is the id of the SQL Server container? Maybe this could give some clue...

**Comment by IoTFier** [comment]
I checked logs output as suggested ... the only new thing I could notice was - databases msdb and  model were up an running after converting those upto version 869 and ports shown below.
Connecting to 127.0.0.1:1434 resulted into the same results
2018-01-22 17:02:30.47 spid19s     Server is listening on [ 'any' <ipv4> 1433].
2018-01-22 17:02:30.48 Server      Server is listening on [ 127.0.0.1 <ipv4> 1434].

I think the Readme.MD file needs to update these connectivity guidelines for both SQL Server and Postgres servers including what data stores are catered by each one of those for which functionalities.

**Digging into a known but hidden treasure is not the way to learn and appreciate all the hardwork put into this great reference app.**

It is getting frustrating ....

**Comment by bradygmsft** [comment]
Thanks for the feedback again, @IoTFier - we'll make sure the README reflects any additional "gotchas" that would impede success. Thanks so much for complementary attitude, too - the team has worked hard on the sample and we're working hard to make sure it's easily consumable. Your feedback is helpful to this end!

**Comment by fpelaez** [comment]
hi @IoTFier , 
could you try to use the IP address of the container followed by comma and then the port number? (localhost,6433 instead of localhost:6433)
<img width="1060" alt="container-sql" src="https://user-images.githubusercontent.com/15648955/35553045-1c6cc568-054b-11e8-878a-325160116fe7.PNG">

**Comment by IoTFier** [comment]
Hi @fpealez. that worked like a charm ! Thank you.
     Would you know where to look for user credentials for B2C, B2E (maintenance) Apps, web site ?
     Are you successful in connecting with Postgres DBs / containers  ?

@bradymsft - Thank you for being there. I agree with you on the fact that this team has worked very hard to build this reference app. I would request us as a community to treat as THE REFERENCE App going forward and keep it up to date with each release of the Visual Studio across all supported GA releases.  I request and encourage you to read my postings from the forum - https://forums.xamarin.com/discussion/comment/317413#Comment_317413

I could finally hear from @jamesmontemagno in the last week.
Thank you

**Comment by bradygmsft** [comment]
Thanks for the answer, @IoTFier, and the continued persistence helping our team get this all buttoned up. Stay tuned, and if you have any updates or tweaks you'd like to make remember, the sample is OSS so a pull request to make it more interesting would be reviewed with enthusiasm! Take care, and happy coding.

**Comment by IoTFier** [comment]
Hi @bradygmsft , I appreciate it.

For the community - I am attaching console output (from building the backend APIs within VS) that lists various database credentials details etc.
[Note- docker-compose.dcproj failed as it refers to building java service. It is being addressed in a separate issue - https://github.com/Microsoft/SmartHotel360/issues/1]

![image](https://user-images.githubusercontent.com/26844611/35582265-f67cd1f4-05b3-11e8-8468-cea8e7c882d7.png)
![image](https://user-images.githubusercontent.com/26844611/35582303-0eb4d730-05b4-11e8-87e1-bae973534022.png)
![image](https://user-images.githubusercontent.com/26844611/35582410-5990c6b0-05b4-11e8-8fab-66fdcebdfb4b.png)
