### ISSUE TITLE
conf_public.yml missing

### ISSUE THREAD

**Issue by SrivatsaMarichi** [Microsoft/SmartHotel360-Azure-backend#13]
Unable to deploy services on the k8s cluster as the conf_public.yml file is missing.

**Comment by bradygmsft** [comment]
Thanks for the report. We'll investigate and work to resolve this. cc @eiximenis

**Comment by eiximenis** [comment]
Hi.
Create your own `conf_public.yml`. Use `conf_local.yml` as a template (basically need to put the connection strings against the azure databases you created).

**Comment by SrivatsaMarichi** [comment]
Cool, I have few doubts to fill in the parameters for couple of values. Need some help.

**Comment by SrivatsaMarichi** [comment]
I was able to deploy, thanks for the help!
