### ISSUE TITLE
Services Not Running Locally

### ISSUE THREAD

**Issue by marwansaab** [Microsoft/SmartHotel360-Azure-backend#14]
After downloading the SmartHotel360-Azure-backend-master and following the instructions - none of the .NET APIs are generating a proper Swagger-UI test page.
Are there any files missing? (ex: there is no "Domain" under "SmartHotel.Services.Profiles"...etc.)
Cheers,
Marwan

**Comment by dixong** [comment]
@marwansaab I had the same problem, the swagger links are adding an extra swagger level to the path.

The Hotels swagger link defaults to http://localhost:6101/swagger/swagger/v1/swagger.json but should just be http://localhost:6101/swagger/v1/swagger.json

I'm not sure why this happens as I don't know enough about the application yet.

**Comment by marwansaab** [comment]
Thank you @dixong - they are running properly now :)
