### ISSUE TITLE
I can't run "docker-compose build" on my mac

### ISSUE THREAD

**Issue by uthens** [Microsoft/SmartHotel360-Azure-backend#16]
I got the some error when i run "docker-compose build"

sql-data uses an image, skipping
Building configuration-api
Step 1/13 : FROM microsoft/aspnetcore:2.0.3 AS base
ERROR: Service 'configuration-api' failed to build: Get https://registry-1.docker.io/v2/microsoft/aspnetcore/manifests/2.0.3: unauthorized: incorrect username or password

**Comment by dasanagu** [comment]
Hi @uthens do you have a docker account? If so, please run docker login, if you don't please proceed to create one, and try docker logout and then docker login. Also please make sure in the docker settings the DNS is set to 8.8.8.8. Let us know the outcome and more than happy to help!

**Comment by bradygmsft** [comment]
@uthens did @dasanagu's suggestion work for you and unblock you? We both ran into this issue the other day so it was fresh on our minds. Please let us know if you're unblocked.
