### ISSUE TITLE
Docs typo

### ISSUE THREAD

**Issue by spacecat** [Microsoft/SmartHotel360-Azure-backend#18]
https://github.com/Microsoft/SmartHotel360-Azure-backend/blob/master/docs/run-azure.md

in one  of the first paragraphs it says "ACS". It should say "AKS".

it is mentioned here as well: orchestratorName: Name of the ACS resource

**Comment by bradygmsft** [comment]
@spacecat thanks for the catch - feel free to submit PRs if you see any other opportunities.
