### ISSUE TITLE
how to know when complete?

### ISSUE THREAD

**Issue by bradygaster** [Microsoft/SmartHotel360-Azure-backend#2]
The `readme.md` file contains the commands to execute to set things up, but doesn't have any commentary on how to verify that the commands/builds worked. As in, the customer has no way to "see the stuff running" on their local machine once the builds have been completed. We need to add something to the `readme.md` to tell the customer how they can tell if they were successful in getting things set up.

**Comment by SrivatsaMarichi** [comment]
@eiximenis IS this being fixed? Because I still get the same error when I access.
