### ISSUE TITLE
"docker-compose build" failing

### ISSUE THREAD

**Issue by stewartnoll** [Microsoft/SmartHotel360-Azure-backend#20]
Get the following error when running `docker-compose build` in the `\src` folder:

```
Step 7/13 : RUN dotnet build -c Release -o /app
 ---> Running in a00a5841ca01
/usr/share/dotnet/sdk/2.0.3/NuGet.targets(102,5): error : An error occurred while retrieving package metadata for 'System.Collections.Concurrent.4.3.0' from source '/usr/share/dotnet/sdk/NuGetFallbackFolder'. [/src/SmartHotel.Services.Configuration.csproj]
/usr/share/dotnet/sdk/2.0.3/NuGet.targets(102,5): error :   '', hexadecimal value 0x03, is an invalid character. Line 1, position 1. [/src/SmartHotel.Services.Configuration.csproj]
ERROR: Service 'configuration-api' failed to build: The command '/bin/sh -c dotnet build -c Release -o /app' returned a non-zero code: 1
```

Anyone else experience this or have a suggestion for getting around it? Running Docker Version 17.12.0-ce-mac49

**Comment by bradygmsft** [comment]
@stewartnoll are you still experiencing this issue? I've been unable to reproduce this - I'm also running Docker on Mac, same version as you.

**Comment by stewartnoll** [comment]
@bradygmsft thanks for checking.  Just tried again after deleting all containers and images and the `configurations-api` built successfully but a similar error happened when it got around to building the `notifications-api`:

```
Step 8/14 : RUN dotnet build -c Release -o /app
 ---> Running in 5d921494abf6
/usr/share/dotnet/sdk/2.0.3/NuGet.targets(102,5): error : An error occurred while retrieving package metadata for 'runtime.native.System.4.3.0' from source '/usr/share/dotnet/sdk/NuGetFallbackFolder'. [/src/SmartHotel.Services.Notifications/SmartHotel.Services.Notifications.csproj]
/usr/share/dotnet/sdk/2.0.3/NuGet.targets(102,5): error :   Data at the root level is invalid. Line 1, position 1. [/src/SmartHotel.Services.Notifications/SmartHotel.Services.Notifications.csproj]
ERROR: Service 'notifications-api' failed to build: The command '/bin/sh -c dotnet build -c Release -o /app' returned a non-zero code: 1
```

**Comment by eiximenis** [comment]
Hi!
0x03 is a ^C character **and it is not a valid XML character according to XML Spec**. 

I opened the file in a binary editor and I don't see 0x03 character. So, it seems something local to your environments.
Could you check with a binary editor that the 1st byte of the csproj is a 0x03 character?
Mine is 0x3C (which is the '<' char).

**Comment by stewartnoll** [comment]
@eiximenis, that was the error I was getting for the `configurations-api` when I reported this but the new error I received yesterday for the `notifications-api` just says `Data at the root level is invalid`.  The git repo is clean but just to be certain I've confirmed that the first byte of `SmartHotel.Services.Notifications.csproj` is 0x3C
<img width="686" alt="screen shot 2018-03-02 at 7 51 21 pm" src="https://user-images.githubusercontent.com/170798/36929194-214ef24c-1e53-11e8-9d82-4d7d9dfea314.png">

and to be doubly-certain I pulled the .csproj from the stopped container using `docker cp <containerId>:/src/SmartHotel.Services.Notifications/SmartHotel.Services.Notifications.csproj temp.csproj` and verified the contents match that from the pasted screenshot above.

**Comment by stewartnoll** [comment]
Well, it looks like the Docker gods have reached down and blessed my mac.  Purged all containers and images and re-ran `docker-compose build` and somehow it got all the way through.  Thanks for your help @eiximenis and @bradygmsft

**Comment by bradygmsft** [comment]
@stewartnoll that's great to hear!
