### ISSUE TITLE
Doc typo was not a typo

### ISSUE THREAD

**Issue by spacecat** [Microsoft/SmartHotel360-Azure-backend#21]
Hi,

Read throught the [gen-k8s-env.ps1](https://github.com/Microsoft/SmartHotel360-Azure-backend/blob/master/deploy/k8s/gen-k8s-env.ps1) file today and the cluster is created in ACS and not AKS. So it was not a typo in the documentation ([the issue I reported the other day](https://github.com/Microsoft/SmartHotel360-Azure-backend/issues/18)).

I guess ACS was used because at the time of when the .ps1 file and SmartHotel360 backend was created AKS was still in beta/preview?

I believe the recommended way of creating a Kubernetes cluster in Azure today is by using AKS (?) and it would be great if SmartHotel360 had scripts for that service as well.

I've followed the AKS quick-start tutorial and it's not that big of a difference (compared to the CLI commands in gen-k8s-env.ps1 for ACS) when creating the cluster so I could probably figure out how to create the resources using AKS instead but maybe it's not that obvious for most people and there could also be some other differences.

**Comment by bradygmsft** [comment]
@spacecat these are great suggestions. @dasanagu and I are working together to create a CICD pipeline that we can use to demonstrate a deployment of the services to AKS. I'll assign this issue to David for the time being as he and I have this in-process. Once we get it complete we'll add some commentary here directing you and other customers who want to see more of the deployment pipeline areas documented more thoroughly.

**Comment by spacecat** [comment]
Sounds great!

**Comment by eiximenis** [comment]
Hi!
I created a `gen-aks-env.ps1` in `deploy/k8s` folder to generate an AKS instead of ACS. Usage is identical to `gen-k8s-env.ps1`.

Also updated doc!
