### ISSUE TITLE
mvnw install fails with err 127 / stream param null

### ISSUE THREAD

**Issue by MFTTech** [Microsoft/SmartHotel360-Azure-backend#8]
When I run docker-compose build:
Step 7/15 : RUN ./mvnw install
 ---> Running in bc9e9d3c2519
/bin/sh: 1: ./mvnw: not found
ERROR: Service 'tasks-api' failed to build: The command '/bin/sh -c ./mvnw install' returned a non-zero code: 127
I'm running this on Win10 Pro with Docker CE and VS15.5.2. Also, when I try and build solution from VS, I get error 
Value cannot be null.
Parameter name: stream	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets 297

**Comment by eiximenis** [comment]
Hi @MFTTech 
 The `Value cannot be null` error that appears in VS is due to a VS bug. I reported an issue to track this in [https://developercommunity.visualstudio.com/content/problem/159711/docker-compose-build-error-value-cannot-be-null-pa.html](https://developercommunity.visualstudio.com/content/problem/159711/docker-compose-build-error-value-cannot-be-null-pa.html)

About the `./mvnw` not found, it should work. Which version of Docker are you using? We use multistage docker files that requires Docker 17.05 or higher.

**Comment by MFTTech** [comment]
Version 17.09.1-ce-win42 (14687)

**Comment by MFTTech** [comment]
Btw, this is a fairly clean msft stack machine. Do I need to have JDK or JRE installed on it?

**Comment by eiximenis** [comment]
No. You don't need anything. Only docker >= 17.05
I think the error is due to a line ending (probably file ends with CRLF and should end only with LF). This is due to a missing .gitattributes file. I will push one later to fix that!

**Comment by MFTTech** [comment]
You are correct. I Changed CRLF to LF in that file but still same issue as other files also have CRLF. Also tried changing existing .gitattributes file eol attribute to CRLF from LF with same result. Not sure if i'll have to resynch repo but anyways, I'll wait for you push and try again.

Thanks!

**Comment by Li-Yanzhi** [comment]
Sames issue occurred here.

**Comment by IoTFier** [comment]
Hi Li-Yanzhi, thank you for your help. I could build docker images successfully at the powershell.
It took around 12 mins 47 seconds for the build to complete for all backend APIs.
Thank you.

**Comment by MFTTech** [comment]
Thanks Li-Yanzhi. That did it!

**Comment by IoTFier** [comment]
Hi Li-Yanzhi / MFTech, this issue isn't ready to be closed yet.

It will be helpful if Li-Yanzhi submits a PR request with the working change recommended by him in master branch. The identified fix in those docker files could be committed as a comment. A comment above that could be added instructing community users to uncomment the line with the proposed fix to help those who will be trying run services in a Docker for Windows environment.

Thoughts?

Thank you.
